release 1.0
semin-alx/java-explore-with-me pull request #1
Opened 2022-09-18 12:50 UTC by semin-alx

2022-09-18 17:40 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе. Будут какие то вопросы, можете писать мне в Slack. Кроме того, обратите внимание, что были типовые комментарии, которые актуальны для нескольких мест в коде, а не только для тех где я их оставил (старался в комментарии подсветить). Жду новую итерацию работы.

2022-09-18 17:40 UTC, Frilock commented on README.md
> +https://github.com/semin-alx/java-explore-with-me/pull/1
Добрый день, хочется в readme увидеть описание проекта, за что каждый модуль отвечает кратко и какие то тонкие подробности, обычно еще пишут как запустить приложение

2022-09-18 17:40 UTC, Frilock commented on expl-me-common/src/main/java/ru/practicum/statistic_dto/EndpointHit.java
> +    @NotBlank
Вообще использование только этой аннотации Вас не защитит от всех случаев с пустым объектом, поскольку может быть 3 варианта: null, "", и "    ". По моему в данной библиотеке для этого нужно использовать три аннотации NotNull, NotEmpty, NotBlank.

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +
Не оставляйте пустые строчки после return

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public CategoryDto create(CategoryDto categoryDto) {
По моему над методами сервиса (если вы используете data-jpa) необходима аннотация Transaction, в других местах об этом писать не буду, проверьте все другие сервисы

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +        return list.toArray(new String[list.size()]);
IDEA предлагает заменить данную строку на return list.toArray(new String[0]);

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/helper/CompilationMapper.java
> +                .map(o -> o.getEventId())
Тут можно заменить на   .map(CompilationEvents::getEventId)

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    List<CompilationEvents> compilationEvents;
А почему модификатор отсутствует?

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    CompilationDto findById(long compId);
Предлагаю тоже отказаться от сокращений comp - compilation

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    private Compilation getAndCheck(Long compId) {
Тело метода можно заменить на 
return compilationRepository.findById(compId)
                .orElseThrow(() -> new ObjectNotFoundException("Указанная подборка не найдена"));
                
                Так будет гораздо компактнее, проверьте в других сервисах аналогичные методы

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        compilationEvents.stream()
stream и forEach вместе не используют, достаточно просто в данном случае compilationEvents.forEach...

Можно заменить на compilationEvents.forEach(compilationEventsRepository::save);

Проверьте в других местах

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/repository/EventRepositoryFilterExImpl.java
> +    public List<Event> findEx(EventFilterParams filterParams, EventSort sort, Pageable pageable) {
Более общий комментарий: вообще в классах, обычно стараются сначала располагать публичные методы, а дальше приватные в порядке их вызова, такой код было бы проще смотреть

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    public EventServiceImpl(EventRepository eventRepository,
Чтобы такие конструкторы не писать большие можно на класс повесить RequiredArgsConstructor от lombok. Но это конечно на ваше усмотрение

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    // Получает с помощью EventMapper EventFullDto из Event
Пользуйтесь не такими комментариями а 
/**
     * 
     */
     
     Где еще можете указать что значат входящие аргументы и результат

2022-09-18 17:40 UTC, Frilock commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (!event.get().getOwner().getId().equals(ownerId)) {
А у нас owner всегда notNull? Тут NPE не получим?

2022-09-19 19:10 UTC, semin-alx commented on Docs/note.txt
> +https://editor-next.swagger.io/
Тесты починили, все работает

2022-09-19 19:10 UTC, semin-alx commented on main-service/src/test/resources/application.properties
> +
Исправил

2022-09-19 19:11 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/model/Statistic.java
> +    private String app;
Добавил

2022-09-19 19:12 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        compilationEvents.stream()
Да, так правильней. Спасибо.

2022-09-19 19:12 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/event/repository/EventRepositoryFilterExImpl.java
> +    public List<Event> findEx(EventFilterParams filterParams, EventSort sort, Pageable pageable) {
исправил

2022-09-19 19:13 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    public EventServiceImpl(EventRepository eventRepository,
Спасибо, действительно, очень удобно.

2022-09-20 19:50 UTC, Frilock requested changes
Добрый вечер, с моей стороны лишь придирки. На часть моих комментариев вы не ответили, часть из них конечно субъективна и остается на Ваше усмотрение, но вы тогда, пожалуйста, напишите в ответе к комментарию, что то вроде - решил оставить так, или если с чем то не согласны тоже можете написать

Ответьте тогда на комментарии и примем работу.

2022-09-20 19:50 UTC, Frilock commented on expl-me-common/src/main/java/ru/practicum/utils/DateTimeUtils.java
> +        } else {
Else не нужен, поскольку если value == null, то будет возвращен null, а иначе и так будет выполнен код дальше.
Относится ко всем трем методам по моему

2022-09-20 19:50 UTC, Frilock commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Вообще тут можно писать так
            <version>${project.version}</version>

Но это не критично, просто в нескольких местах при обновлении версии придется менять ее.

2022-09-20 19:50 UTC, Frilock commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +package ru.practicum.common.error_handling;
В именовании пакетов не принято использовать _. Лучше два вложенных сделать, или как то по другому обозвать его

2022-09-20 19:50 UTC, Frilock commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +
Я у Вас во многих местах вижу, что вы либо в начале либо в конце метода оставляете пустую строчку, зачем? Вам так удобнее? Строчку пустую после return лучше все же убирать

2022-09-20 19:50 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @Column(name = "pinned", nullable = true)
nullable = true, является дефолтным и его можно не указывать

2022-09-20 19:50 UTC, Frilock commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        Optional<CompilationEvents> ce =
Вообще в java не приняты такие сокращения, лучше просто назовите - event/events

2022-09-20 20:54 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/controller/StatisticController.java
> +            @RequestParam(required = true) String start,
исправлено

2022-09-20 21:03 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +        StatisticInfo si = statisticRepository.getStatistic(date1, date2, uri);
Да, так более понятно, переименовал.

2022-09-20 21:04 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +    private Optional<ViewStats> getViewStatistic(LocalDateTime date1, LocalDateTime date2,
Переименовал.

2022-09-20 21:08 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +            if (unique) {
Да, в подобных if-else это выглядит лучше. Заменил.

2022-09-20 21:13 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +            if (stat.isPresent()) {
Java очень богата на разные написания :) Да, такой код лаконичнее.

2022-09-20 21:14 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/service/StatisticServiceImpl.java
> +    public void add(EndpointHit endpointHit) {
Ответил в Slack.

2022-09-20 21:17 UTC, semin-alx commented on statistic-service/src/main/resources/schema.sql
> +    app VARCHAR(100) NOT NULL,
Нет, во втором обновлении это исправлено.

2022-09-20 21:26 UTC, semin-alx commented on README.md
> +https://github.com/semin-alx/java-explore-with-me/pull/1
Написал

2022-09-20 21:31 UTC, semin-alx commented on expl-me-common/src/main/java/ru/practicum/statistic_dto/EndpointHit.java
> +    @NotBlank
Нет, NotBank достаточно.
https://www.baeldung.com/java-bean-validation-not-null-empty-blank
@NotBlank: a constrained String is valid as long as it's not null, and the trimmed length is greater than zero.

2022-09-20 21:34 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +
Первый раз столкнулся с таким замечанием, буду переучиваться :)

2022-09-20 21:41 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public CategoryDto create(CategoryDto categoryDto) {
Из наших уроков: Транзакция объединяет последовательность действий в одну операцию по принципу всё или ничего.

Если мы выполняем только одну SQL команду (INSERT, UPDATE, DELETE), то в данном случае нам не нужно 
открывать самим транзакцию (помечать аннотацией наш метод). Если мы выполняем несколько SQL команд, то в этих случаях да, нужно.

2022-09-20 21:49 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +        return list.toArray(new String[list.size()]);
Да, возможно, так лучше.

2022-09-20 21:52 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/helper/CompilationMapper.java
> +                .map(o -> o.getEventId())
Этот код стал другим (Были изменения в спецификации, как выяснилось по тестам)

2022-09-20 21:53 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    List<CompilationEvents> compilationEvents;
Пропустил, добавил

2022-09-20 21:57 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationService.java
> +    CompilationDto findById(long compId);
Исправил

2022-09-21 08:27 UTC, semin-alx commented on statistic-service/src/main/java/ru/practicum/helper/StatisticMapper.java
> +        LocalDateTime hitTime;
Ок

2022-09-21 08:30 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +    private Compilation getAndCheck(Long compId) {
Да, при работе с  Optional это очень хороший вариант, спасибо.

2022-09-21 08:32 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    // Получает с помощью EventMapper EventFullDto из Event
Исправил

2022-09-21 08:33 UTC, semin-alx commented on expl-me-common/src/main/java/ru/practicum/utils/DateTimeUtils.java
> +        } else {
Да, это я чего-то тормазнул :)

2022-09-21 08:39 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +package ru.practicum.common.error_handling;
Переименовал

2022-09-21 08:42 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +
Идеально это так?
Нет пустой строки после { и до }
-------------------------------------------------------
    public void deleteById(long id) {
        User user = userRepository.findById(id)
                .orElseThrow(() -> new ObjectNotFoundException("Пользователь с таким id в базе не найден"));

        userRepository.deleteById(id);
    }
-------------------------------------------------------

2022-09-21 08:44 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @Column(name = "pinned", nullable = true)
С другой стороны можно посмотреть, как  сделан акцент, что он nullable, а не просто забыл написать. :)

2022-09-21 08:45 UTC, semin-alx commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        Optional<CompilationEvents> ce =
Исправил

2022-09-21 16:03 UTC, Frilock commented on main-service/src/main/java/ru/practicum/common/error_handling/ApiError.java
> +
У Вас вот так
  private Optional<ViewStats> getViewStatistic(LocalDateTime start, LocalDateTime end,
                                                 String uri, boolean unique) {

        StatisticInfo info = statisticRepository.getStatistic(start, end, uri);

        if (info == null) {
            return Optional.empty();
        }

        long count = unique ? info.getCountUniqIp() : info.getCountAll();

        return Optional.of(new ViewStats(info.getAppName(), uri, count));

    }
    
    На мой взгляд идеально так
      private Optional<ViewStats> getViewStatistic(LocalDateTime start, LocalDateTime end,
                                                 String uri, boolean unique) {
        StatisticInfo info = statisticRepository.getStatistic(start, end, uri);

        if (info == null) {
            return Optional.empty();
        }

        long count = unique ? info.getCountUniqIp() : info.getCountAll();

        return Optional.of(new ViewStats(info.getAppName(), uri, count));
    }

2022-09-21 16:04 UTC, Frilock approved these changes
Работу принял, мне в целом все понравилось. Удачи!

2022-09-26 13:35 UTC, merged